### ISSUE TITLE
May I ask why I could merge it as transparent png?

### ISSUE THREAD

**Issue by aetherwu** [ozankasikci/go-image-merge#10]
I'm sorry to trouble you here.

I used code below to render my multiple layers to a single image:
```
layers := getInputLayers() // slice of files in string
grids := []*gim.Grid{
{ImageFilePath: "input/" + layers[6]},
{ImageFilePath: "input/" + layers[5]},
{ImageFilePath: "input/" + layers[4]},
}
rgba, err := gim.New(grids, 1, 1).Merge()
file, err := os.Create("output/images/path.png")
err = png.Encode(file, rgba)
```

All layers that I've used are transparent which can be merged/combined in other program/software.
However I always got the top layer with solid rendering with my code.

May I ask for some help? 
Appreciate your time and attention.

**Comment by aetherwu** [comment]
Ok. So I have to use nested config it seems.
It feels pretty weired if I would like to merge more layers on top of eath.

**Comment by ozankasikci** [comment]
Hi, the library doesn't take into account the transparency of the images, so indeed you need to use nested grids.

**Comment by aetherwu** [comment]
Thanks very much :D
