### ISSUE TITLE
0.3.0 only have internal folder

### ISSUE THREAD

**Issue by 766b** [ozankasikci/go-image-merge#12]
Am I missing something? 0.3.0 only have internal folder and nothing else, can't really import it into project this way.

**Comment by ozankasikci** [comment]
oh you are right 😅 I'll make the library importable.

**Comment by ozankasikci** [comment]
@766b released a new version v0.3.1, the library is now importable again.

**Comment by ozankasikci** [comment]
Please Let me know if it works so I can close the issue.
